#!/bin/sh

INTOPTIONS=3,4,7
PEAKOPTIONS=3,4,7
FILELIST=$1
GEOMETRY=$2
CELL=/das/work/p17/p17491/Cecilia_Casadei/TR-SFX/bR_TR_SFX/published_pipeline/indexing_2/BR.cell
GEOM=/das/work/p17/p17491/Cecilia_Casadei/TR-SFX/bR_TR_SFX/published_pipeline/indexing_2/$GEOMETRY

#list_events -i $FILELIST -g $GEOM -o events-${FILELIST}.lst

        sbatch -p day -t 23:00:00 <<EOF
#!/bin/bash

cd ${PWD}

module load psi-python27/2.3.0
module load gcc/4.9.2
module load openmpi/1.8.4
module load hdf5/1.8.14
module load xds/15.10.2015
module load ccp4/7.0
source /opt/psi/MX/ccp4/7.0/ccp4-7.0/bin/ccp4.setup-sh
module load DirAx/1.16
module load psdm/0.17.19
source /opt/psi/MX/psdm/0.17.19/etc/ana_env.sh
module unload crystfel
module load crystfel/0.6.3

NPROC=\`grep proc /proc/cpuinfo | wc -l \`

indexamajig -i $FILELIST -o ${FILELIST}.stream -j \$NPROC -g $GEOM  --peaks=cxi --indexing=dirax,mosflm --integration=rings --int-radius=${INTOPTIONS} \
--peak-radius=${PEAKOPTIONS} -p ${CELL} &> ${FILELIST}.log 

EOF

