clear;
path = '/das/work/p17/p17491/Cecilia_Casadei/NLSA/data_rho/preliminary_NLSA/';
folder = 'data_rho_2/data_extraction/';
fn = 'data_rho_light_sorted_SCL_nS278263_nBrg74887';          
data_file = [path, folder, fn, '.mat'];
            
fn = [path, folder, 'timestamps_light_sorted.mat']; 
load(fn, 'timestamps_light_sort');

fn = [path, folder, 'partialator_OK_light_sorted.mat']; 
load(fn, 'uniqueID_light_sort')

Index = find(contains(uniqueID_light_sort,'/rho_nlsa_scan_19/'));

uniqueID_selected = uniqueID_light_sort(Index);
timestamps_selected = timestamps_light_sort(Index);

load(data_file, 'M_scl', ...
                'T_scl', ...
                'miller_h', ...
                'miller_k', ...
                'miller_l')

M_selected = M_scl(Index,:);
T_selected = T_scl(Index,:);

fn_save = [path, folder, 'light_scan_19_sorted_SCL', '.mat'];
save(fn_save, ...
        'T_selected', ...
        'M_selected', ...
        'miller_h', ...
        'miller_k', ...
        'miller_l', ...
        'uniqueID_selected', ...
        'timestamps_selected', ...
        '-v7.3');